name: Deploy Theme
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: TryGhost/action-deploy-theme@v1.4.1
        with:
          api-url: ${{ secrets.https://chvblog.herokuapp.com }}
          api-key: ${{ secrets.349b09caf134a4b8cff016b9fa }}
          theme-name: "casper-rtl"
